name: Test
run-name: Ejecutar tests
on: [push, pull_request]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        run: |
          cd calculadora
          npm install

      - name: Ejecutar tests
        run: |
          cd calculadora
          npm run test
